services:
  postgres_database:
    container_name: postgres-container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: uberheat

  redis:
    container_name: redis-container
    image: redis
    restart: always
    ports:
      - 6379:6379
