services:
  postgres_database:
    container_name: postgres-container-cms
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: miniature-cms

  redis:
    container_name: redis-container-cms
    image: redis
    restart: always
    ports:
      - 6379:6379
